apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: centos
      command: [ "sleep",  "5000" ]
      resources:
        limits:
          hdls.me/sdx: "1"
        requests:
          hdls.me/sdx: "1"