project_name: node-device-plugin
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: plugin-darwin-amd64
    ldflags: -s -w -X github.com/zwwhdls/node-device-plugin/version.gitCommit={{.ShortCommit}}
    main: .
    goos:
      - darwin
    goarch:
      - amd64
  - id: plugin-darwin-arm64
    ldflags: -s -w -X github.com/zwwhdls/node-device-plugin/version.gitCommit={{.ShortCommit}}
    main: .
    goos:
      - darwin
    goarch:
      - arm64
  - id: plugin-linux-amd64
    ldflags: -s -w -X github.com/zwwhdls/node-device-plugin/version.gitCommit={{.ShortCommit}}
    main: .
    goos:
      - linux
    goarch:
      - amd64
  - id: plugin-linux-arm64
    ldflags: -s -w -X github.com/zwwhdls/node-device-plugin/version.gitCommit={{.ShortCommit}}
    main: .
    goos:
      - linux
    goarch:
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
